### ISSUE TITLE
Consistent use of primers throughout pipeline

### ISSUE THREAD

**Issue by martinghunt** [iqbal-lab-org/viridian_workflow#102]
Expected behaviour: the amplicon scheme and the primers used are inferred early on in the pipeline. Some primers can be identified as not present in the reads. These primers should be completely excluded from everything onwards.

Actual behaviour: inconsistent use of whether primers are present or not.

See comment "The logic for identifying primers before cylon is run is different than the later primer id logic that we use to mask primer positions in the consensus." https://github.com/iqbal-lab-org/viridian_workflow/issues/99#issuecomment-1274638945

**Comment by jeff-k** [comment]
Identifying which primers belonging to an amplicon are observed among all fragments belonging to that amplicon is a subtly different task than identifying which primer appears in a fragment.

I agree that it would have been nice to retain the original consistent logic but the solution that we arrived at ultimately requires that these operations require different logic.

**Comment by martinghunt** [comment]
IIRC the plan was always to remove primers in the way I just described. And be consistent throughout.

**Comment by iqbal-lab** [comment]
This issue is about
 - if an alt primer is excluded from the scheme and removed before passing to cylon, it shoudl be excluded forever
 It is not about the primer-id having different implementations at the start and in selfQC

**Comment by jeff-k** [comment]
Yes, that is what we do

**Comment by iqbal-lab** [comment]
yeah the point is, we excliude it when passing to cylon, but it comes back by the time we get to selfQC
