### ISSUE TITLE
Mask final consensus positions 

### ISSUE THREAD

**Issue by martinghunt** [iqbal-lab-org/viridian_workflow#18]
At the end of the pipeline when mapping to viridian output, need to mask positions where >50% of reads disagree with the consensus sequence (can happen in rare cases when viridian has an error).

**Comment by jeff-k** [comment]
I've pushed a hacky pass at this: positions that appear in the first `max primer_length` bases from the 5' ends of reads don't contribute to the consensus disagreement count
