### ISSUE TITLE
JSON Format Question

### ISSUE THREAD

**Issue by andypowelloracle** [iqbal-lab-org/viridian_workflow#35]
Is there an importance to the number on the read_sampling objects in the output JSON? Example: "SARS-CoV-2_1" or "SARS-CoV-2_2" 
If there isn't a specific importance to the trailing number on those object keys, it would be great to place that in a JSON Array instead of objects with unique keys.

Something like:
"read_sampling": {
    "SARS-CoV-2": [
            {
                 "start": 26,
                 ...
                 "pass": false
            },
            {
                 "start": 325,
                 ...
                 "pass": false
            }
    ]
}

**Comment by martinghunt** [comment]
The keys are the names of the amplicons. The format of those names could be anything, and indeed do vary between ARTIC v3, ARTIV v4, and midnight. It's extremely useful to be able to look up an amplicon by name, hence why it's a hash of name -> info.
