### ISSUE TITLE
Suitability of 'Sydney' scheme for autodetection

### ISSUE THREAD

**Issue by bede** [iqbal-lab-org/viridian_workflow#77]
I've tested the following scheme working as a forced scheme, and wonder whether this scheme—very different to any other scheme I have encountered—is a good candidate for autodetection and further testing as a built in scheme

[covid-sydney.vwf.tsv.txt](https://github.com/iqbal-lab-org/viridian_workflow/files/9093914/covid-sydney.vwf.tsv.txt)

**Comment by iqbal-lab** [comment]
I'd like to propose,  since you'll be getting informed by your users @bede  that this is the scheme they're using, that you/gpas simply specify the scheme in the command line invocation of viridian. I think nick built this functionality in already. Anyway,  will discuss at this end.
