### ISSUE TITLE
Immediate issues to be combined into new tag for testing

### ISSUE THREAD

**Issue by iqbal-lab** [iqbal-lab-org/viridian_workflow#79]
- [x] new cte
- [x] new varifier
- [x] reduce stringency of filter for what % of reads must match the amplicon scheme up front
- [x] check the ref-N-ref-N thing

**Comment by jeff-k** [comment]
Sorry, what was the "ref-N-ref-N" thing again?

**Comment by iqbal-lab** [comment]
July 7th post in viridian validation channel, @martinghunt was seeing stuff like this

==> ERR8959186/per_position.tsv <==
29825   G   G   G   True_ref    Called_ref
29826   T   T   T   True_ref    Called_ref
29827   A   A   A   True_ref    Called_ref
29828   G   G   N   True_ref    Called_N
29829   T   T   N   True_ref    Called_N
29830   G   G   N   True_ref    Called_N
29831   C   C   N   True_ref    Called_N
29832   T   T   N   True_ref    Called_N
29833   A   A   N   True_ref    Called_N
29834   T   T   N   True_ref    Called_N
29835   C   C   N   True_ref    Called_N
29836   C   C   N   True_ref    Called_N
29837   C   C   N   True_ref    Called_N
29838   C   C   C   True_ref    Called_ref
29839   A   A   A   True_ref    Called_ref
29840   T   T   N   True_ref    Called_N
29841   G   G   N   True_ref    Called_N
29842   T   T   N   True_ref    Called_N
29843   G   G   G   True_ref    Called_ref
29844   A   A   N   True_ref    Called_N
29845   T   T   N   True_ref    Called_N
29846   T   T   N   True_ref    Called_N

These might even be related to the spikes Martin is looking at now. I think we can't roll this into the same issue. I propose the spikes are a separate issue.

**Comment by martinghunt** [comment]
Spikes separate. IIRC the ref-N-ref-N thing was caused by the MSA doing global align right to the ends of both genomes, which is now fixed.

**Comment by iqbal-lab** [comment]
in that case we can close!
