### ISSUE TITLE
If users want to force scheme, let them 

### ISSUE THREAD

**Issue by iqbal-lab** [iqbal-lab-org/viridian_workflow#87]
In the case where the user forces a specific primer scheme, we run our checks to compare the reads with that scheme (and potentially various inbuilt schemes). We may in this case find the reads don't match any scheme (as far as our filters/criteria go): if so we should warn, but go ahead and try to assemble - otherwise we're subverting the meaning of force in the force option.

**Comment by jeff-k** [comment]
This sounds like the current behaviour of the `--force_amp_scheme` option, do we have an example of the expected output vs. subverted output?

**Comment by iqbal-lab** [comment]
That's the expected current behaviour of that option, i think it got turned off during refactoring. in terms of expected behaviour, i would just run 0.3.7, which does support this - we just want to maintain that behaviour

**Comment by jeff-k** [comment]
I'm not sure when it may have been broken/turned-off, but this has been and still is the behaviour

**Comment by iqbal-lab** [comment]
hurrah!

**Comment by martinghunt** [comment]
Here's an example of when it was broken.

Although forcing now looks fixed on refactor 2022 branch, the json entry for results -> amplicons -> scheme contains info on the scheme that would have been chosen, not on the scheme that was forced.

<img width="923" alt="image" src="https://user-images.githubusercontent.com/4937411/194129164-d1f127d8-b9da-45ef-a8bc-f851c1ba34b4.png">
