### ISSUE TITLE
Output of tsv as commandline option

### ISSUE THREAD

**Issue by iqbal-lab** [iqbal-lab-org/viridian_workflow#89]
Not sure if this is done - if so what is the cli and what is the default? Is it included in the stuff that gets deleted in auto-cleanup? Seems like it should not be.

Also have i raised this issue before?

**Comment by jeff-k** [comment]
There is a `--dump-tsv` argument that writes out an exhaustive per-position tsv file:

```
singularity exec vwf-aug3-test.img viridian_workflow run_one_sample --dump_tsv --tech illumina --ref MN908947.fasta --outdir /tmp/out --reads1 sample_R1.fastq.gz --reads2 sample_R2.fastq.gz
```
